import Fastify from 'fastify';
import cors from '@fastify/cors';
import jwt from '@fastify/jwt';
import Database from 'better-sqlite3';
import bcrypt from 'bcryptjs';
import { createHash, randomUUID } from 'node:crypto';
import { mkdirSync } from 'node:fs';
import { z } from 'zod';

mkdirSync('data', { recursive: true });
const db = new Database('data/jocky.db');
db.pragma('journal_mode = WAL');
db.exec(`
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,name TEXT NOT NULL,role TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS endpoints (id TEXT PRIMARY KEY,hostname TEXT UNIQUE NOT NULL,os TEXT NOT NULL,ip TEXT NOT NULL,agent_version TEXT,capabilities TEXT NOT NULL,status TEXT NOT NULL,last_seen TEXT,created_at TEXT NOT NULL,created_by TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS investigations (id TEXT PRIMARY KEY,name TEXT NOT NULL,source TEXT NOT NULL,targets TEXT NOT NULL,status TEXT NOT NULL,created_by TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS evidence (id TEXT PRIMARY KEY,investigation_id TEXT NOT NULL,endpoint_id TEXT NOT NULL,collector TEXT NOT NULL,artifact_type TEXT NOT NULL,content TEXT NOT NULL,sha256 TEXT NOT NULL,metadata TEXT NOT NULL,collected_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS custody (id TEXT PRIMARY KEY,evidence_id TEXT NOT NULL,actor TEXT NOT NULL,action TEXT NOT NULL,metadata TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY,actor TEXT NOT NULL,action TEXT NOT NULL,resource TEXT NOT NULL,resource_id TEXT,metadata TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS scripts (id TEXT PRIMARY KEY,name TEXT NOT NULL,source TEXT NOT NULL,created_by TEXT NOT NULL,updated_at TEXT NOT NULL);
`);

type User = { id:string; email:string; name:string; role:string };
const app = Fastify({ logger: true });
await app.register(cors,{origin:true});
await app.register(jwt,{secret:process.env.JWT_SECRET || 'local-development-only-change-this'});
const now=()=>new Date().toISOString();
const id=()=>randomUUID();
function audit(actor:string,action:string,resource:string,resourceId:string|undefined,metadata:unknown={}){db.prepare('INSERT INTO audit_logs VALUES (?,?,?,?,?,?,?)').run(id(),actor,action,resource,resourceId??null,JSON.stringify(metadata),now())}
async function actor(req:any):Promise<User>{return await req.jwtVerify() as User}
function must(role:string[], user:User){if(!role.includes(user.role)) throw Object.assign(new Error('Insufficient permission'),{statusCode:403});}
const ops = [
 ['SYSTEM.INFO',['windows','linux'],[], 'Host system profile'],['SYSTEM.USERS',['windows','linux'],[],'Local user inventory'],['SYSTEM.SERVICES',['windows','linux'],[],'Service inventory'],['SYSTEM.STARTUP',['windows','linux'],[],'Startup entry inventory'],['PROCESS.LIST',['windows','linux'],[],'Running process artifacts'],['PROCESS.TREE',['windows','linux'],[],'Process-parent relationships'],['NETWORK.CONNECTIONS',['windows','linux'],[],'Active network connections'],['NETWORK.LISTENING',['windows','linux'],[],'Listening network sockets'],['FILE.MODIFIED',['windows','linux'],['PATH','SINCE'],'Modified file artifacts'],['FILE.HASH',['windows','linux'],['PATH'],'File hash artifacts'],['EVENTS.LOGIN',['windows','linux'],['SINCE'],'Authentication events'],['TIMELINE.CREATE',['core'],[],'Normalized timeline build'],['CORRELATE',['core'],[],'Evidence relationship analysis'],['EVIDENCE.PRESERVE',['core'],[],'Evidence integrity preservation'],['REPORT.GENERATE',['core'],['FORMAT'],'Reproducible report creation']
];
function parse(source:string){const errors:{line:number;message:string}[]=[];const plan:any[]=[]; const lines=source.split('\n'); let name='Untitled investigation';let targets=''; let opened=false;
 lines.forEach((raw,i)=>{const line=raw.trim(); if(!line||line.startsWith('//'))return; if(/^INVESTIGATION\s+".+"\s*\{$/.test(line)){name=line.match(/"(.+)"/)![1];opened=true;return} if(line==='}'){opened=false;return} if(!opened){errors.push({line:i+1,message:'Expected INVESTIGATION block'});return} if(line.startsWith('TARGETS ')){const m=line.match(/group\("([\w-]+)"\)/); if(!m) errors.push({line:i+1,message:'TARGETS requires group("name")'}); else targets=m[1];return} const operation=(line.match(/(?:COLLECT\s+)?([A-Z]+\.[A-Z_]+)/)||[])[1] || (line.startsWith('CORRELATE')?'CORRELATE':undefined); if(!operation){errors.push({line:i+1,message:'Unknown JOCKY statement'});return} const op=ops.find(x=>x[0]===operation); if(!op){errors.push({line:i+1,message:`Unknown operation ${operation}`});return} for(const required of op[2] as string[]){if(!new RegExp(`\\b${required}\\s+`).test(line)) errors.push({line:i+1,message:`${operation} requires ${required}`})} const since=line.match(/SINCE\s+"([^"]+)"/)?.[1]; if(since&&!/^\d+[mhd]$/.test(since)) errors.push({line:i+1,message:`Invalid time expression "${since}"`}); plan.push({operation,line:i+1,parameters:{path:line.match(/PATH\s+"([^"]+)"/)?.[1],since,format:line.match(/FORMAT\s+"([^"]+)"/)?.[1]}})});
 if(opened) errors.push({line:lines.length,message:'Missing closing }'}); if(!targets) errors.push({line:1,message:'Investigation requires TARGETS group("name")'}); return {valid:errors.length===0,errors,ast:{type:'Investigation',name,targets,operations:plan},plan};
}

app.get('/health',async()=>({status:'ok',service:'jocky-api',time:now()}));
app.post('/api/v1/auth/register',async(req,reply)=>{const body=z.object({email:z.string().email(),password:z.string().min(12),name:z.string().min(2)}).parse(req.body); const existing=db.prepare('SELECT id FROM users WHERE email=?').get(body.email); if(existing)return reply.code(409).send({message:'Email already registered'}); const user={id:id(),email:body.email,name:body.name,role:'FORENSIC_ADMIN'}; db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?)').run(user.id,user.email,await bcrypt.hash(body.password,12),user.name,user.role,now());audit(user.email,'user.registered','user',user.id);return {token:app.jwt.sign(user),user};});
app.post('/api/v1/auth/login',async(req,reply)=>{const body=z.object({email:z.string().email(),password:z.string()}).parse(req.body);const row:any=db.prepare('SELECT * FROM users WHERE email=?').get(body.email);if(!row||!(await bcrypt.compare(body.password,row.password_hash)))return reply.code(401).send({message:'Invalid credentials'});const user={id:row.id,email:row.email,name:row.name,role:row.role};audit(user.email,'user.logged_in','session',undefined);return {token:app.jwt.sign(user),user};});
app.get('/api/v1/operations',async()=>ops.map(([id,platforms,required,description])=>({id,platforms,required,description,risk:'LOW',allowlisted:true})));
app.get('/api/v1/templates',async(req)=>{await actor(req);return [
 {id:'suspicious-endpoint',name:'Suspicious Endpoint Activity',description:'Processes, network, file hash and authentication evidence.',source:`INVESTIGATION "Suspicious Endpoint Activity" {\n  TARGETS group("finance-endpoints")\n  COLLECT SYSTEM.INFO\n  COLLECT PROCESS.LIST\n  COLLECT PROCESS.TREE\n  COLLECT NETWORK.CONNECTIONS\n  COLLECT FILE.HASH PATH "/Users/analyst/Downloads/invoice_update.exe"\n  COLLECT EVENTS.LOGIN SINCE "24h"\n  TIMELINE.CREATE\n  CORRELATE PROCESS FILE NETWORK EVENT\n  EVIDENCE.PRESERVE\n  REPORT.GENERATE FORMAT "PDF"\n}`},
 {id:'persistence-sweep',name:'Persistence Sweep',description:'Startup and service inventory for authorized endpoints.',source:`INVESTIGATION "Persistence Sweep" {\n  TARGETS group("authorized-endpoints")\n  COLLECT SYSTEM.SERVICES\n  COLLECT SYSTEM.STARTUP\n  COLLECT FILE.MODIFIED PATH "/ProgramData" SINCE "24h"\n  TIMELINE.CREATE\n  EVIDENCE.PRESERVE\n  REPORT.GENERATE FORMAT "PDF"\n}`},
 {id:'authentication-review',name:'Authentication Review',description:'Cross-host login event review with correlation.',source:`INVESTIGATION "Authentication Review" {\n  TARGETS group("authorized-endpoints")\n  COLLECT SYSTEM.USERS\n  COLLECT EVENTS.LOGIN SINCE "24h"\n  COLLECT NETWORK.CONNECTIONS\n  TIMELINE.CREATE\n  CORRELATE PROCESS NETWORK EVENT\n  EVIDENCE.PRESERVE\n  REPORT.GENERATE FORMAT "PDF"\n}`}
]});
app.post('/api/v1/jocky/validate',async(req)=>{await actor(req);return parse(z.object({source:z.string().min(1)}).parse(req.body).source)});
app.post('/api/v1/scripts',async(req)=>{const user=await actor(req);must(['SUPER_ADMIN','FORENSIC_ADMIN','INVESTIGATOR'],user);const b=z.object({name:z.string().min(2),source:z.string().min(1)}).parse(req.body);const scriptId=id();db.prepare('INSERT INTO scripts VALUES (?,?,?,?,?)').run(scriptId,b.name,b.source,user.id,now());audit(user.email,'script.saved','script',scriptId);return {id:scriptId,name:b.name,updatedAt:now()};});
app.get('/api/v1/detections',async(req)=>{await actor(req);const rows:any[]=db.prepare('SELECT e.*,ep.hostname FROM evidence e JOIN endpoints ep ON ep.id=e.endpoint_id').all();const detections=rows.flatMap(e=>{const text=JSON.stringify(e.content);const hit=text.includes('JOCKY-SAFE-TEST-IOC-001');return hit?[{id:e.id,severity:'HIGH',title:'Local test IOC matched',hostname:e.hostname,collector:e.collector,sha256:e.sha256,rule:'JOCKY-TEST-IOC-001',note:'Benign local test indicator; no malicious code was executed.'}]:[]});return detections});
app.post('/api/v1/local/reset-runs',async(req)=>{const user=await actor(req);must(['SUPER_ADMIN','FORENSIC_ADMIN'],user);const result=db.transaction(()=>{db.prepare('DELETE FROM custody').run();const evidenceCount=db.prepare('DELETE FROM evidence').run().changes;const investigationCount=db.prepare('DELETE FROM investigations').run().changes;db.prepare('DELETE FROM audit_logs').run();audit(user.email,'local.run_history_reset','local-data',undefined,{localOnly:true});return {evidenceCount,investigationCount}})();return {message:'Local investigation history, evidence, custody, and audit records were cleared. Endpoints, accounts, and saved scripts were preserved.',...result}});
app.get('/api/v1/endpoints',async(req)=>{await actor(req);return db.prepare('SELECT * FROM endpoints ORDER BY created_at DESC').all().map((x:any)=>({...x,capabilities:JSON.parse(x.capabilities)}));});
app.post('/api/v1/endpoints',async(req,reply)=>{const user=await actor(req);must(['SUPER_ADMIN','FORENSIC_ADMIN'],user);const b=z.object({hostname:z.string().min(2),os:z.enum(['windows','linux']),ip:z.string().ip(),agentVersion:z.string().min(1),capabilities:z.array(z.string()).min(1)}).parse(req.body);const endpoint={id:id(),hostname:b.hostname,os:b.os,ip:b.ip,agentVersion:b.agentVersion,capabilities:b.capabilities,status:'ENROLLED'};try{db.prepare('INSERT INTO endpoints VALUES (?,?,?,?,?,?,?,?,?,?)').run(endpoint.id,endpoint.hostname,endpoint.os,endpoint.ip,endpoint.agentVersion,JSON.stringify(endpoint.capabilities),endpoint.status,null,now(),user.id)}catch{return reply.code(409).send({message:'Hostname already enrolled'})}audit(user.email,'endpoint.enrolled','endpoint',endpoint.id,{hostname:endpoint.hostname});return reply.code(201).send(endpoint)});
app.get('/api/v1/investigations',async(req)=>{await actor(req);return db.prepare('SELECT * FROM investigations ORDER BY created_at DESC').all().map((x:any)=>({...x,targets:JSON.parse(x.targets)}));});
app.post('/api/v1/investigations',async(req,reply)=>{const user=await actor(req);must(['SUPER_ADMIN','FORENSIC_ADMIN','INVESTIGATOR'],user);const b=z.object({source:z.string().min(1),endpointIds:z.array(z.string()).min(1)}).parse(req.body);const result=parse(b.source);if(!result.valid)return reply.code(422).send(result);const found=db.prepare(`SELECT id FROM endpoints WHERE id IN (${b.endpointIds.map(()=>'?').join(',')})`).all(...b.endpointIds);if(found.length!==b.endpointIds.length)return reply.code(422).send({message:'One or more endpoints are not enrolled'});const investigation={id:id(),name:result.ast.name,source:b.source,targets:b.endpointIds,status:'PLANNED'};db.prepare('INSERT INTO investigations VALUES (?,?,?,?,?,?,?,?)').run(investigation.id,investigation.name,investigation.source,JSON.stringify(investigation.targets),investigation.status,user.id,now(),now());audit(user.email,'investigation.created','investigation',investigation.id,{targets:b.endpointIds.length});return reply.code(201).send({...investigation,plan:result.plan});});
app.post('/api/v1/investigations/:id/start',async(req,reply)=>{const user=await actor(req);must(['SUPER_ADMIN','FORENSIC_ADMIN','INVESTIGATOR'],user);const inv:any=db.prepare('SELECT * FROM investigations WHERE id=?').get((req.params as any).id);if(!inv)return reply.code(404).send({message:'Investigation not found'});db.prepare('UPDATE investigations SET status=?,updated_at=? WHERE id=?').run('RUNNING',now(),inv.id);const targetIds:string[]=JSON.parse(inv.targets);if(process.env.JOCKY_DEMO_MODE!=='false'){for(const [index,endpointId] of targetIds.entries()){const ep:any=db.prepare('SELECT hostname,os FROM endpoints WHERE id=?').get(endpointId);if(!ep)continue;const flagged=index===0;const content={host:ep.hostname,platform:ep.os,process:{pid:4102,executable:flagged?'jocky-safe-test-observation':'approved-system-observation',user:'local-demo'},network:{remoteAddress:flagged?'198.51.100.42':'192.0.2.10',remotePort:443},indicator:flagged?'JOCKY-SAFE-TEST-IOC-001':undefined,note:flagged?'Local test indicator. No malicious code was executed.':'Local simulator clean observation.'};const payload=JSON.stringify(content);const evidenceId=id();const hash=createHash('sha256').update(payload).digest('hex');db.prepare('INSERT INTO evidence VALUES (?,?,?,?,?,?,?,?,?,?)').run(evidenceId,inv.id,endpointId,'SIMULATOR.ADAPTER','normalized-observation',payload,hash,JSON.stringify({adapter:'local-simulator',integrity:'VERIFIED',demo:true,classification:flagged?'TEST_IOC':'CLEAN'}),now(),now());db.prepare('INSERT INTO custody VALUES (?,?,?,?,?,?)').run(id(),evidenceId,'local-simulator','COLLECTED',JSON.stringify({sha256:hash,integrity:'VERIFIED'}),now())}db.prepare('UPDATE investigations SET status=?,updated_at=? WHERE id=?').run('COMPLETED',now(),inv.id);audit(user.email,'investigation.demo_completed','investigation',inv.id,{adapter:'local-simulator',targets:targetIds.length,flaggedTargets:targetIds.length?1:0});return {id:inv.id,status:'COMPLETED',demo:true,message:`Local simulator completed: 1 test indicator flagged and ${Math.max(0,targetIds.length-1)} clean endpoint result(s) stored.`}}audit(user.email,'investigation.started','investigation',inv.id);return {id:inv.id,status:'RUNNING',message:'Jobs are ready for enrolled agents. No evidence is generated until an authenticated agent submits a signed collector result.'}});
app.post('/api/v1/agent/evidence',async(req,reply)=>{const b=z.object({investigationId:z.string().uuid(),endpointId:z.string().uuid(),collector:z.string().min(3),artifactType:z.string().min(2),content:z.unknown(),metadata:z.record(z.string(),z.unknown()).default({})}).parse(req.body);const endpoint:any=db.prepare('SELECT * FROM endpoints WHERE id=?').get(b.endpointId);if(!endpoint)return reply.code(404).send({message:'Endpoint is not enrolled'});const payload=JSON.stringify(b.content);const evidence={id:id(),sha256:createHash('sha256').update(payload).digest('hex')};db.prepare('INSERT INTO evidence VALUES (?,?,?,?,?,?,?,?,?,?)').run(evidence.id,b.investigationId,b.endpointId,b.collector,b.artifactType,payload,evidence.sha256,JSON.stringify(b.metadata),now(),now());db.prepare('INSERT INTO custody VALUES (?,?,?,?,?,?)').run(id(),evidence.id,endpoint.hostname,'COLLECTED',JSON.stringify({sha256:evidence.sha256,collector:b.collector}),now());db.prepare('UPDATE endpoints SET last_seen=?,status=? WHERE id=?').run(now(),'ONLINE',b.endpointId);audit(endpoint.hostname,'evidence.collected','evidence',evidence.id,{sha256:evidence.sha256});return reply.code(201).send({evidenceId:evidence.id,sha256:evidence.sha256,integrity:'VERIFIED'});});
app.get('/api/v1/evidence',async(req)=>{await actor(req);return db.prepare('SELECT e.*,ep.hostname FROM evidence e JOIN endpoints ep ON ep.id=e.endpoint_id ORDER BY collected_at DESC').all().map((x:any)=>({...x,content:JSON.parse(x.content),metadata:JSON.parse(x.metadata)}));});
app.get('/api/v1/audit',async(req)=>{await actor(req);return db.prepare('SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT 200').all().map((x:any)=>({...x,metadata:JSON.parse(x.metadata)}));});
app.setErrorHandler((error:any,_req,reply)=>reply.code(error.statusCode||400).send({message:error.message||'Request failed'}));
app.listen({port:Number(process.env.PORT||3201),host:'0.0.0.0'});
